voiceapp/urls.py
from django.urls import path
from . import views
 
urlpatterns= [
    path('',views.home,name="home"),
    path('dashboard',views.dashboard,name="dashboard"),
    path('testing/', views.testing, name='testing'),
    # path('register',views.register,name="register"),
    # path('login',views.login_page,name="login"),
    # path('logout',views.logout_page,name="logout"),
    # path('logout/', views.logoutUser, name="logout"),
    # path('cart',views.cart_page,name="cart"),
    # path('fav',views.fav_page,name="fav"),
    # path('favviewpage',views.favviewpage,name="favviewpage"),
    # path('remove_fav/<str:fid>',views.remove_fav,name="remove_fav"),
    # path('remove_cart/<str:cid>',views.remove_cart,name="remove_cart"),
    # path('collections',views.collections,name="collections"),
    # path('collections/<str:name>',views.collectionsview,name="collections"),
    # path('collections/<str:cname>/<str:pname>',views.product_details,name="product_details"),
    # path('addtocart',views.add_to_cart,name="addtocart"),
]

voiceshare/urls.py
from django.contrib import admin
from django.urls import path,include
 
from django.conf import settings
from django.conf.urls.static import static
 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('voiceapp.urls')),
]
 
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Voice Admin"
admin.site.site_title = "Voice Admin Portal"
admin.site.index_title = "Welcome to Voice"

voiceapp/models.py
from itertools import product
from django.db import models
# from django.contrib.auth.models import User
import datetime
import os
from django.contrib.auth.models import Group

from django.contrib.auth import get_user_model
User = get_user_model()

def getFileName(requset,filename):
  now_time=datetime.datetime.now().strftime("%Y%m%d%H:%M:%S") + '_'
  new_filename="%s%s"%(now_time,filename)
  return os.path.join('uploads/',new_filename)
 
class User_Voice(models.Model):
  from_user_name=models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='from_user_name')
  to_user_name=models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='to_user_name')
  voice_file=models.FileField(upload_to=getFileName)
  description=models.TextField(max_length=500,null=False,blank=False)
  status=models.BooleanField(default=False,help_text="0-show,1-Hidden")
  created_at=models.DateTimeField(auto_now_add=True)
 
  def __str__(self):
    return f"{self.from_user_name}, {self.to_user_name}, {self.voice_file}"

class Catagory(models.Model):
  name=models.CharField(max_length=150,null=False,blank=False)
  image=models.ImageField(upload_to=getFileName,null=True,blank=True)
  description=models.TextField(max_length=2500,null=False,blank=False)
  status=models.BooleanField(default=False,help_text="0-show,1-Hidden")
  created_at=models.DateTimeField(auto_now_add=True)
 
  def __str__(self) :
    # return f"{self.name}, {self.description}, {self.created_at}"
    return self.name

  @property
  def get_audios(self):
     return Audio.objects.filter(category__root=(...))
  
class Audio(models.Model):
  # Catagory_name=models.ForeignKey(Catagory, on_delete=models.DO_NOTHING, related_name='Catagory_name')
  Catagory_name=models.ForeignKey(Catagory, on_delete=models.DO_NOTHING)
  name=models.CharField(max_length=150,null=False,blank=False)
  audio_file=models.FileField(upload_to=getFileName,null=True,blank=True)
  description=models.TextField(max_length=2500,null=False,blank=False)
  status=models.BooleanField(default=False,help_text="0-show,1-Hidden")
  created_at=models.DateTimeField(auto_now_add=True)

  def __str__(self) :
    return f"{self.Catagory_name}, {self.name}, {self.audio_file}, {self.created_at}"

class Audio_User(models.Model): 
  # Audio_name=models.ForeignKey(Audio, on_delete=models.DO_NOTHING, related_name='Audio_name')
  # User_name=models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='User_name')
  Audio_name=models.ForeignKey(Audio, on_delete=models.DO_NOTHING)
  User_name=models.ForeignKey(User, on_delete=models.DO_NOTHING)

  def __str__(self) :
    return f"{self.Audio_name}, {self.User_name}"
  
class Audio_Group(models.Model): 
  Audio_name=models.ForeignKey(Audio, on_delete=models.DO_NOTHING)
  Group_name=models.ForeignKey(Group, on_delete=models.DO_NOTHING)

  def __str__(self) :
    return f"{self.Audio_name}, {self.Group_name}"

voiceapp/views.py
from django.http import  JsonResponse
from django.shortcuts import redirect, render
from voiceapp.form import CustomUserForm
from . models import *
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
import json

from django.http import HttpResponse
from django.db import connection
from django.template import loader

def testing(request):
  template = loader.get_template('template.html')
  context = {
    'fruits': ['You', 'Me', 'Us'],   
  }
  return HttpResponse(template.render(context, request))

# def dashboard(request):
#   # books is app name and book is model
#     query = "SELECT * FROM voiceapp.voiceapp_audio_user;"
 
#     with connection.cursor() as cursor:
#         cursor.execute(query)
#         results = cursor.fetchall()
 
#     table_html = "<table><tr><th>Title</th><th>Author</th><th>Publication Year</th></tr>"
#     for row in results:
#         table_html += f"<tr><td>{row[1]}</td><td>{row[2]}</td><td></td></tr>"
#     table_html += "</table>"
 
#     # Pass the table_html to the template
#     return render(request, 'voiceapp/categories.html', {'table_html': table_html})

def dashboard(request):
#   categories=Audio.objects.select_related('Catagory_name')
#   # categories=Audio_User.objects.select_related('Audio_name').all()
#   print(categories.count())
#   return render(request,"voiceapp/index.html",{"categories":categories})
    
    categorys = Catagory.objects.all()
    audios = Audio.objects.all()
    audio_users = Audio_User.objects.all()

    context = {
        "categorys":categorys,
        'audios':audios,
        'audio_users':audio_users
    }

    return render(request, 'voiceapp/categories.html', context)
 
   
def home(request):
  products=Audio.objects.filter(Catagory_name_id=1)
  return render(request,"voiceapp/index.html",{"products":products})
  return render(request,"voiceapp/index.html")
  #return render(request,"voiceapp/login.html")
 
# def favviewpage(request):
#   if request.user.is_authenticated:
#     fav=Favourite.objects.filter(user=request.user)
#     return render(request,"voiceapp/fav.html",{"fav":fav})
#   else:
#     return redirect("/")
 
# def remove_fav(request,fid):
#   item=Favourite.objects.get(id=fid)
#   item.delete()
#   return redirect("/favviewpage")
 
 
 
 
# def cart_page(request):
#   if request.user.is_authenticated:
#     cart=Cart.objects.filter(user=request.user)
#     return render(request,"voiceapp/cart.html",{"cart":cart})
#   else:
#     return redirect("/")
 
# def remove_cart(request,cid):
#   cartitem=Cart.objects.get(id=cid)
#   cartitem.delete()
#   return redirect("/cart")
 
 
 
# def fav_page(request):
#    if request.headers.get('x-requested-with')=='XMLHttpRequest':
#     if request.user.is_authenticated:
#       data=json.load(request)
#       product_id=data['pid']
#       product_status=Product.objects.get(id=product_id)
#       if product_status:
#          if Favourite.objects.filter(user=request.user.id,product_id=product_id):
#           return JsonResponse({'status':'Product Already in Favourite'}, status=200)
#          else:
#           Favourite.objects.create(user=request.user,product_id=product_id)
#           return JsonResponse({'status':'Product Added to Favourite'}, status=200)
#     else:
#       return JsonResponse({'status':'Login to Add Favourite'}, status=200)
#    else:
#     return JsonResponse({'status':'Invalid Access'}, status=200)
 
 
# def add_to_cart(request):
#    if request.headers.get('x-requested-with')=='XMLHttpRequest':
#     if request.user.is_authenticated:
#       data=json.load(request)
#       product_qty=data['product_qty']
#       product_id=data['pid']
#       #print(request.user.id)
#       product_status=Product.objects.get(id=product_id)
#       if product_status:
#         if Cart.objects.filter(user=request.user.id,product_id=product_id):
#           return JsonResponse({'status':'Product Already in Cart'}, status=200)
#         else: 
#           if product_status.quantity>=product_qty:
#             Cart.objects.create(user=request.user,product_id=product_id,product_qty=product_qty)
#             return JsonResponse({'status':'Product Added to Cart'}, status=200)
#           else:
#             return JsonResponse({'status':'Product Stock Not Available'}, status=200)
#     else:
#       return JsonResponse({'status':'Login to Add Cart'}, status=200)
#    else:
#     return JsonResponse({'status':'Invalid Access'}, status=200)
 
# def logout_page(request):
#   messages.success(request,"Logged out Successfully")
#   if request.user.is_authenticated:
#     logout(request)
#     messages.success(request,"Logged out Successfully")
#   return redirect("/")

# def logout_view(request):
#     logout(request)
#     return redirect('/')
 
# def login_page(request):
#   if request.user.is_authenticated:
#     return redirect("/")
#   else:
#     if request.method=='POST':
#       name=request.POST.get('username')
#       pwd=request.POST.get('password')
#       user=authenticate(request,username=name,password=pwd)
#       if user is not None:
#         login(request,user)
#         messages.success(request,"Logged in Successfully")
#         return redirect("/")
#       else:
#         messages.error(request,"Invalid User Name or Password")
#         return redirect("/login")
#     return render(request,"voiceapp/login.html")
 
# def register(request):
#   form=CustomUserForm()
#   if request.method=='POST':
#     form=CustomUserForm(request.POST)
#     if form.is_valid():
#       form.save()
#       messages.success(request,"Registration Success You can Login Now..!")
#       return redirect('/login')
#   return render(request,"voiceapp/register.html",{'form':form})
 
 
# def collections(request):
#   catagory=Catagory.objects.filter(status=0)
#   return render(request,"voiceapp/collections.html",{"catagory":catagory})
 
# def collectionsview(request,name):
#   if(Catagory.objects.filter(name=name,status=0)):
#       products=Product.objects.filter(category__name=name)
#       return render(request,"voiceapp/products/index.html",{"products":products,"category_name":name})
#   else:
#     messages.warning(request,"No Such Catagory Found")
#     return redirect('collections')
 
 
# def product_details(request,cname,pname):
#     if(Catagory.objects.filter(name=cname,status=0)):
#       if(Product.objects.filter(name=pname,status=0)):
#         products=Product.objects.filter(name=pname,status=0).first()
#         return render(request,"voiceapp/products/product_details.html",{"products":products})
#       else:
#         messages.error(request,"No Such Produtct Found")
#         return redirect('collections')
#     else:
#       messages.error(request,"No Such Catagory Found")
#       return redirect('collections')

templates/voiceapp/audio_attribue.html
{% extends 'admin/base_site.html' %}
{% load i18n admin_urls %}
{% load static %}

{% block title %}
Voice Share | Voice Share App
{% endblock title %}

{% block content %}

  <div class="container">
    <!-- <div class="row"> -->
      <div class="col-12">
        <h3 class="mb-3"> Audio attribué </h3>
        <hr style="border-color:#b8bfc2;">
      </div>
     
      <div class="row">
        <div class="col-12">
        <div class="card" style="margin-bottom: 10px;">
            <div class="container" style="background-color: #F2F3F4;">
              <table>
                {% for audio in Audios %}
                  <div class="float-child" style="float: left; text-align: center; width: 35%; padding: 10px;" >
                    <i class="fa fa-file-audio" style="font-size:50px;color:red"></i>
                    <h6 style="height: 50px;" ><b>{{ audio.name }}</b></h6>
                    <h5><audio controls><source src="https://rajesh1872.pythonanywhere.com/static/{{audio.audio_file}}" type="audio/mpeg"></audio></h5>
                  </div>
                {% endfor %}
              </table>
            </div>
          </div>       
          </div>                                                                                              
        </div> 
      
    <!-- </div> -->
  </div>
{% endblock content %}

      

templates/voiceapp/categories.html
{% extends 'admin/base_site.html' %}
{% load i18n admin_urls %}
{% load static %}

{% block title %}
Voice Share | Voice Share App
{% endblock title %}

{% block content %}

  <div class="container">
    <div class="row">
      <div class="col-12">
        <h3 class="mb-3"> Tous les audios </h3>
        <hr style="border-color:#b8bfc2;">
      </div>

      {% for category in categorys %}
        <div class="row">
        <div class="col-12">
            <p></p>
        <h4>{{ category.name }} &nbsp;&nbsp;&nbsp;<a class="ibutton" href="https://rajesh1872.pythonanywhere.com/admin/voiceapp/catagory/{{ category.id }}/change/"><i class="fa fa-edit"></i></a></h4>
        
        {% for audio in category.audio_set.all %}
        <div class="row">
            <div class="col-12">
            <div class="card" style="margin-bottom: 10px;">
                <div class="container" style="background-color: #F2F3F4;">
                    <h6><b>{{ audio.name }} &nbsp;&nbsp;&nbsp;<a class="ibutton" href="https://rajesh1872.pythonanywhere.com/admin/voiceapp/audio/{{ audio.id }}/change/"><i class="fa fa-edit"></i></a></b></h6>
                    <h6><audio controls><source src="https://rajesh1872.pythonanywhere.com/static/{{audio.audio_file}}" type="audio/mpeg"></audio></h6>
                    <h6><p>{{ audio.description }}</p></h6>            
                    <h6>
                        <p>Users:            
                            {% for audio_user in audio.audio_user_set.all %}
                                <!-- https://rajesh1872.pythonanywhere.com/admin/voiceapp/audio_user/3/change/ -->
                                <a href="https://rajesh1872.pythonanywhere.com/admin/auth/user/{{ audio_user.User_name_id }}/change/">{{ audio_user.User_name }},</a>
                            {% endfor %}    
                        </p>
                    </h6>
                </div>
            </div>      
          </div>                                                                                              
        </div>              
        {% endfor %}
      {% endfor %}
        </div>
        </div>
      <p></p>
    </div>
  </div>
{% endblock content %}

      

templates/voiceapp/collaborateurs.html
{% extends 'admin/base_site.html' %}
{% load i18n admin_urls %}
{% load static %}

{% block title %}
Voice Share | Voice Share App
{% endblock title %}

{% block content %}

  <div class="container">
    <!-- <div class="row"> -->
      <div class="col-12">
        <h3 class="mb-3"> Collaborateurs </h3>
        <hr style="border-color:#b8bfc2;">
      </div>

      <div class="col-12">
        <h4 class="blue mb-3"> <a href="https://rajesh1872.pythonanywhere.com/admin/auth/user/"> Utilisateurs </a></h4>
      </div>
      
      {% for user in Users %}
        <div class="row">
          <div class="col-12">
          <div class="card" style="margin-bottom: 5px;">
              <div class="container" style="padding: 0%;">
                <div class="float-child" style="width: 40%;float: left; background-color: #F2F3F4; height: 90px; padding-left: 10px;">
                  <p><h5>{{ user.first_name }} {{ user.last_name }} </h5> </p>
                  <p>
                    <h6>
                        <p>Équipe:            
                            {% if user.groups.all %}
                              {% for usergroup in user.groups.all %}
                                <a href="https://rajesh1872.pythonanywhere.com/admin/auth/group/{{ usergroup.id }}/change/">{{ usergroup.name }},</a>
                              {% endfor %}    
                            {% else %}
                              Non attribuée
                            {% endif %}
                        </p>
                    </h6>
                </p>
              </div>
              <div class="float-child" style="width: 50%;float: left; background-color: #F2F3F4; height: 90px; padding-top: 15px;">
                <p>{{ user.email }}</p>
                <p><p><h6>&nbsp;&nbsp;&nbsp;</h6></p></p></p>
              </div>
              <div class="float-child" style="width: 10%;float: left; background-color: #fff; height: 90px; padding-top: 15px; padding-left: 10px; border-radius: 10px;">
                <p><a class="blue" href="https://rajesh1872.pythonanywhere.com/admin/auth/user/{{ user.id }}/change/">Modifier</a></p>
                <p><a class="red" href="https://rajesh1872.pythonanywhere.com/admin/auth/user/{{ user.id }}/delete/">Supprimer</a></p>
              </div>
            </div>
          </div>      
          </div>                                                                                              
        </div> 
      {% endfor %}
    <!-- </div> -->
  </div>
      
  <p></p>
  <div class="container">
    <!-- <div class="row"> -->
      <div class="col-12">
        <h4 class="blue mb-3"> <a href="https://rajesh1872.pythonanywhere.com/admin/auth/group/"> Groupes </a></h4>
      </div>

      {% for group in Groups %}
      <div class="row">
        <div class="col-12">
          <div class="card" style="margin-bottom: 10px;">
            <div class="container" style="padding: 0%;">

              <div class="float-child" style="width: 40%;float: left; background-color: #F2F3F4; height: 90px; padding-left: 10px; padding-top: 15px;">
                <!-- <div class="container" style="background-color: #F2F3F4;"> -->
                  <h5>{{ group.name }}</h5>
                <!-- </div> -->
              </div>
              
              <div class="float-child" style="width: 50%;float: left; background-color: #F2F3F4; height: 90px; padding-left: 10px; padding-top: 15px;">
                <!-- <div class="container" style="background-color: #F2F3F4;"> -->
                  {% if group.user_set.all %}                    
                      {% for user in group.user_set.all %}
                        <h6>{{ user.first_name }} {{ user.last_name }},</h6>
                      {% endfor %}    
                  {% endif %}
                <!-- </div> -->
              </div>
              <div class="float-child" style="width: 10%;float: left; background-color: #fff; height: 90px; padding-left: 10px; padding-top: 15px; border-radius: 10px;">
                <p><a class="blue" href="https://rajesh1872.pythonanywhere.com/admin/auth/group/{{ group.id }}/change/">Modifier</a></p>
                <p><a class="red" href="https://rajesh1872.pythonanywhere.com/admin/auth/group/{{ group.id }}/delete/">Supprimer</a></p>
              </div>
            </div>
          </div>
        </div>                                                                                                  
      </div> 
      {% endfor %}
    <!-- </div> -->
  </div>      
{% endblock content %}

      

templates/voiceapp/fichiers_reçus.html
{% extends 'admin/base_site.html' %}
{% load i18n admin_urls %}
{% load static %}

{% block title %}
Voice Share | Voice Share App
{% endblock title %}

{% block content %}

  <div class="container">
    <!-- <div class="row"> -->
      <div class="col-12">
        <h3 class="mb-3"> Fichiers reçus </h3>
        <hr style="border-color:#b8bfc2;">
      </div>
     
      <div class="row">
        <div class="col-12">
        <div class="card" style="margin-bottom: 10px;">
            <div class="container" style="background-color: #F2F3F4;">
              <table>
              {% for audio in Audios %}
                <div class="float-child" style="float: left; text-align: center; width: 20%; padding: 10px;" >
                  <a href="https://rajesh1872.pythonanywhere.com/static/{{audio.audio_file}}" target="_blank"><i class="fa fa-file-audio" style="font-size:50px;color:red"></i></a>
                  <p style="height: 50px; font-size: small; font-weight:bold;" >{{ audio.audio_file }}</p>
                  <p style="font-size: small;" >{{ audio.created_at }}</p>
                  <button class="btn-purple-moon" style="margin-bottom: 10px;" onclick="window.location.href = 'https://rajesh1872.pythonanywhere.com/admin/voiceapp/audio_user/add/';"> Ajouter</button>
                </div>
              {% endfor %}
              </table>
            </div>
          </div>       
          </div>                                                                                              
        </div> 
      
    <!-- </div> -->
  </div>
{% endblock content %}

      

templates/voiceapp/index.html
{% extends 'voiceapp/layouts/main.html' %}
{% block title %}
Voice Share | Voice Share App
{% endblock title %}

{% block content %}
{% include 'voiceapp/inc/slider.html' %}
  <div class="container" style="margin-top:70px;" >
    <div class="row">
      <div class="col-12">
        <h4 class="mb-3"> Categories </h4>
        <hr style="border-color:#b8bfc2;">
      </div>
      {% for item in categories %}
        <!-- <h4 class="mb-3"> products in</h4> -->
        <div class="col-md-6 col-lg-3">
          <div class="card" style="width: 400px;">
            <div class="container" style="padding-left: var(--bs-gutter-x,1.75rem);">
                <h3><b>{{ item.Catagory_name }} </b></h3>
                <p>{{ item.name }}</p>
                <audio controls><source src="https://rajesh1872.pythonanywhere.com/static/{{item.audio_file}}" type="audio/mpeg"></audio>
                <p>{{ item.description }}</p>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock content %}      

templates/voiceapp/login.html
{% extends 'voiceapp/layouts/main.html' %}
{% block title %}
  Login | Voice App
{% endblock title %}
{% block content %}
  <div class="container" style="margin-top:70px;min-height:600px;">
    <div class="row">
      <div class="col-12">
        <h4 class="mb-3"> User Login</h4>
        <hr style="border-color:#b8bfc2;">
        {% include 'voiceapp/inc/message.html' %}
      </div>
    </div>
    <section class="py-4" >
      <div class="container">
        <div class="row">
          <div class="col-6">
            <form method="post" action="">
              {% csrf_token %}
              <div class="mb-4">
                <label for="" class="form-label">User Name</label>
                <input type="text" name="username" id="username" class="form-control" placeholder="Enter User Name">
              </div>
              <div class="mb-4">
                <label for="" class="form-label">Password</label>
                <input type="password" name="password" id="password" class="form-control" placeholder="Enter Password">
              </div>
              <button type="submit" class="btn btn-primary">Login</button>
            </form>
          </div>
        </div>
      </div>
    </section>
  </div>
{% endblock content %}

templates/voiceapp/register.html
{% extends 'voiceapp/layouts/main.html' %}
{% block title %}
  Registration | Voice App
{% endblock title %}
{% block content %}
{% include 'voiceapp/inc/slider.html' %}
  <div class="container" style="margin-top:70px;min-height:600px;">
    <div class="row">
      <div class="col-12">
        <h4 class="mb-3"> New User Registration</h4>
        <hr style="border-color:#b8bfc2;">
        {% include 'voiceapp/inc/message.html' %}
      </div>
    </div>
    <section class="py-4" >
      <div class="container">
        <div class="row">
          <div class="col-6">
            <form method="post" action="">
              {% csrf_token %}
              <div class="mb-4">
                <label for="" class="form-label">User Name</label>
                {{form.username}}
              </div>
              <div class="mb-4">
                <label for="" class="form-label">User Email</label>
                {{form.email}}
              </div>
              <div class="mb-4">
                <label for="" class="form-label">Password</label>
                {{form.password1}}
              </div>
              <div class="mb-4">
                <label for="" class="form-label">Confirm Password</label>
                {{form.password2}}
              </div>
              <button type="submit" class="btn btn-primary">Register</button>
            </form>
            <p class="my-2">Already user ? <a href="{% url 'login' %}">Login Now</a> </p>
          </div>
          <div class="col-6">
            
                {% if form.errors.username %}
                  <label class="text-danger d-block">{{ form.errors.username }}</label>
                {% endif %}
            
                {% if form.errors.email %}
                <label class="text-danger d-block">{{ form.errors.email }}</label>
                {% endif %}
              
                {% if form.errors.password1 %}
                <label class="text-danger d-block">{{ form.errors.password1 }}</label>
                {% endif %}
              
                {% if form.errors.password2 %}
                <label class="text-danger d-block">{{ form.errors.password2 }}</label>
                {% endif %}
              
          </div>
        </div>
      </div>
    </section>
  </div>
{% endblock content %}

templates/voiceapp/voice.html
{% extends 'shop/layouts/main.html' %}
{% block title %}
  Registration | ShopKart
{% endblock title %}
{% block content %}
  <section class="bg-light py-4 my-5" style="min-height:600px;">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <h4 class="mb-3">Voice</h4>
          <hr style="border-color:#b8bfc2;">
        </div>
      
        <table>
            <tr>
                <th>Image</th>
                <th>Product Name</th>
                <th>Unit</th>
                <th>Quantity</th>
                <th>Amount</th>
                <th>Remove</th>
            </tr>
          

            {% for item in cart %}
           <tr>
              <td><img src="{{item.product.product_image.url}}" height="75px" alt="{{item.product.name}}"></td>
              <td>{{item.product.name}}</td>
              <td>{{item.product.selling_price | stringformat:'d'}}</td>
              <td>{{item.product_qty}}</td>
              <td class="amt">{{item.total_cost | stringformat:'d'}}</td>
              <td><a href="{% url 'remove_cart' item.id %}"  onclick="return confirm('Are you sure? to Remove')"  class="btn btn-danger btn-sm"><i class="fa fa-trash"></i> Remove</a></td>
            </tr>
            {% endfor %}
            <tr>
              <td></td>
              <td></td>
              <td colspan="2"><b>Total Amount</b></td>
              <th id="net">0</th>
              <td><button class="btn btn-primary btn-sm">
                <i class="fa fa-check-circle"></i> Check Out
              </button></td>
            </tr>
           
        </table>
       
      </div>
      </div>
  </section>

  <script>
    const nodes = document.querySelectorAll('.amt');
    const arr = Array.from(nodes);
    const res = arr.reduce((acc, curr) => {
     return acc += Number(curr.textContent)
    }, 0);
    document.getElementById("net").innerHTML="Rs : "+res;

  </script>
{% endblock content %}